### ISSUE TITLE
Exception in Tkinter callback Traceback (most recent call last):   File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in __call__     return self.func(*args)   File "C:\Users\user\Desktop\main.py", line 551, in <lambda>     sb= Button(al, text= "LOGIN", fg="white", bg="#1966ff", command= lambda: admin_auth(e1.get(),e2.get()))   File "C:\Users\user\Desktop\main.py", line 516, in admin_auth     ad(username)   File "C:\Users\user\Desktop\main.py", line 486, in ad     t9 = change_price_of_item(tab_main, username)   File "C:\Users\user\Desktop\main.py", line 98, in change_price_of_item     clicked.set(options[0]) IndexError: list index out of range *HOW TO SOLVE THIS ERROR*

### ISSUE THREAD

**Issue by KES2619** [anpct/billingsystem#2]

**Comment by anpct** [comment]
I have updated _createdb.py_ please run that file again, it should work

**Comment by anpct** [comment]
I have also updated main.py to prevent this issue

**Comment by KES2619** [comment]
Thank you sir

**Comment by KES2619** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in
__call__
    return self.func(*args)
  File "C:\Users\user\Desktop\main.py", line 377, in <lambda>
    b2 = Button(t, text="SUBMIT", command=lambda: get_bill(
  File "C:\Users\user\Desktop\main.py", line 318, in get_bill
    cost = cost + i[2]
TypeError: unsupported operand type(s) for +: 'int' and 'str'
AGAIN ERROR SIR IM SO SORRY FOR DISTURBING

**Comment by anpct** [comment]
change it from `cost = cost + i[2]` to `cost = cost + int(i[2])`

**Comment by KES2619** [comment]
It is fixed.
thankyou for helping ,you are a really nice person.

**Comment by anpct** [comment]
Feel free to reach out if you have any problems

**Comment by KES2619** [comment]
sir do have the synopsis of this project?

**Comment by anpct** [comment]
email me at: anthiparala@gmail.com

**Comment by KES2619** [comment]
SIR there is again and issue the user dash wont open
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in
__call__
    return self.func(*args)
  File "C:\Users\user\Desktop\main.py", line 555, in <lambda>
    command=lambda: user_auth(e1.get(), e2.get()))
  File "C:\Users\user\Desktop\main.py", line 526, in user_auth
    ud(username)
  File "C:\Users\user\Desktop\main.py", line 482, in ud
    t2 = bill(tab_main, username)
  File "C:\Users\user\Desktop\main.py", line 403, in bill
    clicked.set(options[0])
IndexError: list index out of range
